/**
 * 🔐 AUTHENTICATION EVENT TYPES
 * Event-driven authentication system for YOLOVibe platform
 */

export const AuthEventTypes = {
  // Login & Session Events
  LOGIN_ATTEMPTED: 'LOGIN_ATTEMPTED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT_INITIATED: 'LOGOUT_INITIATED',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_VALIDATED: 'SESSION_VALIDATED',
  SESSION_INVALID: 'SESSION_INVALID',
  
  // Registration Events
  REGISTRATION_ATTEMPTED: 'REGISTRATION_ATTEMPTED',
  REGISTRATION_SUCCESS: 'REGISTRATION_SUCCESS',
  REGISTRATION_FAILED: 'REGISTRATION_FAILED',
  EMAIL_VERIFICATION_SENT: 'EMAIL_VERIFICATION_SENT',
  EMAIL_VERIFIED: 'EMAIL_VERIFIED',
  
  // Password Reset Events
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_EMAIL_SENT: 'PASSWORD_RESET_EMAIL_SENT',
  PASSWORD_RESET_TOKEN_VALIDATED: 'PASSWORD_RESET_TOKEN_VALIDATED',
  PASSWORD_RESET_SUCCESS: 'PASSWORD_RESET_SUCCESS',
  PASSWORD_RESET_FAILED: 'PASSWORD_RESET_FAILED',
  
  // Security Events
  SUSPICIOUS_LOGIN_ATTEMPT: 'SUSPICIOUS_LOGIN_ATTEMPT',
  MULTIPLE_FAILED_ATTEMPTS: 'MULTIPLE_FAILED_ATTEMPTS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_UNLOCKED: 'ACCOUNT_UNLOCKED',
  
  // Portal Access Events
  PORTAL_ACCESS_GRANTED: 'PORTAL_ACCESS_GRANTED',
  PORTAL_ACCESS_DENIED: 'PORTAL_ACCESS_DENIED',
  WORKSHOP_MATERIAL_ACCESSED: 'WORKSHOP_MATERIAL_ACCESSED',
  PROGRESS_UPDATED: 'PROGRESS_UPDATED'
} as const;

export type AuthEventType = typeof AuthEventTypes[keyof typeof AuthEventTypes]; 